spring:
  application:
    name: say-hello

server:
  port: 8090
### CSE configurations #########
cse:
  credentials:
    accessKey: BUDCVWSAW04UZVLSZBQR
    secretKey: BHixEctCJFbTkPUVUUjRDSeVwMAknlAy5oB7idgR
    akskCustomCipher: default
### END OF CSE configurations #########