server:
  port: 9090
spring:
  application:
    name: spring-cloud-demo
### CSE configurations #########
cse:
  credentials:
    accessKey: BUDCVWSAW04UZVLSZBQR
    secretKey: BHixEctCJFbTkPUVUUjRDSeVwMAknlAy5oB7idgR
    akskCustomCipher: default
### END OF CSE configurations #########